version: "3.8"

services:
  # Serviço da aplicação Node.js
  backend:
    image: node:16 # Ou a versão que você preferir
    container_name: menu-api
    working_dir: /app
    volumes:
      - ./src:/app # Mapeia o diretório 'src' para o diretório no container
    ports:
      - "3000:3000" # Porta exposta para acessar o backend
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/menuapp
    command: "npm start" # Comando para iniciar a aplicação
    depends_on:
      - mongo
    networks:
      - app-network

  # Serviço do banco de dados MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017" # Porta do MongoDB
    volumes:
      - mongo_data:/data/db # Persistência de dados
    networks:
      - app-network

# Definição da rede e volume persistente
networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
